/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simrat kaur gill
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(null);

        lb1.setIcon(new javax.swing.ImageIcon("C:\\Users\\simrat kaur gill\\Downloads\\pci.png")); // NOI18N
        lb1.setText("jLabel1");
        add(lb1);
        lb1.setBounds(10, 30, 300, 220);

        lb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 204, 204));
        lb2.setText("jLabel2");
        add(lb2);
        lb2.setBounds(20, 300, 100, 40);

        lb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(153, 255, 255));
        lb3.setText("jLabel3");
        add(lb3);
        lb3.setBounds(20, 370, 110, 22);

        lb4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb4.setForeground(new java.awt.Color(153, 255, 255));
        lb4.setText("jLabel4");
        add(lb4);
        lb4.setBounds(20, 430, 130, 22);

        lb5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb5.setForeground(new java.awt.Color(153, 255, 255));
        lb5.setText("jLabel5");
        add(lb5);
        lb5.setBounds(20, 490, 150, 22);

        lb6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb6.setForeground(new java.awt.Color(153, 255, 255));
        lb6.setText("jLabel6");
        add(lb6);
        lb6.setBounds(20, 550, 140, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public javax.swing.JLabel lb3;
    public javax.swing.JLabel lb4;
    public javax.swing.JLabel lb5;
    public javax.swing.JLabel lb6;
    // End of variables declaration//GEN-END:variables
}
